### ISSUE TITLE
ResNet-50 Trained Model 

### ISSUE THREAD

**Issue by ildoonet** [bayesgroup/gps-augment#1]
While I have tried to reproduce your result, I faced few problems.

1. no timm module

```
ModuleNotFoundError                       Traceback (most recent call last)
/data/private/gps-augment/imagenet/get_preds_randaug_imagenet.py in <module>
      7 from imagenet.randaugment_imagenet import BetterRandAugment, getRandomResizedCropAndInterpolationdef
      8 import torchvision.transforms as transforms
----> 9 from timm.models import create_model
     10 import torchvision.datasets as datasets
     11 from PIL import Image

ModuleNotFoundError: No module named 'timm'
```

I guess you used this : https://github.com/rwightman/pytorch-image-models

I copied the module from the repository, but I don't have the trained model you used.

2. You used ResNet-50 model with 79.2% top-1 accuracy on ImageNet, which trained with AugMix and RandAugment as you wrote in your paper. But I can't find the weight file in the repository.

**Comment by senya-ashukha** [comment]
Hi Ildoo, I deeply apologize for the late replay.

1. Yes,  https://github.com/rwightman/pytorch-image-models is the correct repo. Regarding the installation prosses, as far as I remember, I used the pip package as suggested here https://rwightman.github.io/pytorch-image-models.

2. We used the following model https://rwightman.github.io/pytorch-image-models/training_hparam_examples/#resnet50-with-jsd-loss-and-randaugment-clean-2x-ra-augs-7904-top-1-9439-top-5 (we should definitely fix the description as it is not quite accurate). The model is called resnet50 in the code and `import timm; m = timm.create_model('resnet50', pretrained=True)` should reproduce the results. The accuracy mismatch 79.04 vs 79.2 is due to using half of the `val` split for evaluation (that is also expressed not clear enough.)

Let us know if you have any further questions!
